# Generated by Django 4.1.4 on 2022-12-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('oficial', 'Oficial'), ('local', 'Local')], max_length=30, null=True),
        ),
    ]
